[Facebook and Webex adapter functional test] Validate required variables to correct inconclusive results
southworks/botbuilder-dotnet pull request #321
Opened 2020-09-02 19:23 UTC by iscaltritti-sw

Fixes Issue# 4545

## Description

> The functional tests currently run and end as Inconclusive, which hides the actual state of the tests. We need to determine if the failures are test issues and if they are, fix them.

The inconclusive result of Facebook's and Webex's tests are a product of required environment variables being un-reachable, which skips the actual functional tests. Our tests ran successfully whenever all environment variables were set up correctly, and we could only replicate the issue's reported behavior when leaving variables null purposefully.

It should be noted that the current inconclusive response is not an issue of the test's implementation. Changing the inconclusive assertions to failures would lead to false negatives, since the tests did not fail, but were **unable to be run**.

Our proposed solution is to integrate a required variable validating task to run prior to all other tasks in the pipeline. This keeps the tests intact and **saves waiting for the pipeline to run until failure** due to missing, empty or white-spaced variables, making those occurrences **easier to catch and correct**.

We validate for required variables mannually on each case, leaving room for custom behavior. It should be noted that we also left the _FacebookTestBotFacebookVerifyToken_ variable on _[botbuilder-dotnet-ci-facebook-test.yml](https://github.com/microsoft/botbuilder-dotnet/blob/main/build/yaml/botbuilder-dotnet-ci-facebook-test.yml)_ unvalidated as it was detected that it was not required for the test to run.

## Specific Changes

- Adds a required variable validation task and skip conditions to subsequent tasks to _[botbuilder-dotnet-ci-webex-test.yml](https://github.com/microsoft/botbuilder-dotnet/blob/main/build/yaml/botbuilder-dotnet-ci-webex-test.yml)_ and _[botbuilder-dotnet-ci-facebook-test.yml](https://github.com/microsoft/botbuilder-dotnet/blob/main/build/yaml/botbuilder-dotnet-ci-facebook-test.yml)_.
- Added an optional clarification and description to _FacebookTestBotFacebookVerifyToken_ variable signature on _[botbuilder-dotnet-ci-facebook-test.yml](https://github.com/microsoft/botbuilder-dotnet/blob/main/build/yaml/botbuilder-dotnet-ci-facebook-test.yml)_ since the variable was detected to not be required.

## Testing

The following image showcases the new task in action. First we deleted required variables, then the task outputs which variables were missing.

![image](https://user-images.githubusercontent.com/64803884/92025680-48959180-ed36-11ea-8b22-21fe9c08791f.png)

We also checked that both Facebook's and Webex's tests were running correctly, which we can corroborate with the following images.

- Facebook:
![image](https://user-images.githubusercontent.com/64803884/92025917-97dbc200-ed36-11ea-94f0-a2be6396a3c9.png)

- Webex:
![image](https://user-images.githubusercontent.com/64803884/92025903-94483b00-ed36-11ea-9f73-1e7cc91ffb8f.png)

2020-09-02 21:16 UTC, ceciliaavila requested changes
Just a small detail in one of the yamls and also please update the PR's description with:
 - `mannually` -> `manually`
 -  In Specific Changes section, keep the sentences in the same tense.

2020-09-02 21:16 UTC, ceciliaavila commented on build/yaml/botbuilder-dotnet-ci-webex-test.yml
>    AppSecret: $(WebexTestBotAppSecret)
Why did you move this variable? They are supposed to be ordered alphabetically.

2020-09-03 19:04 UTC, sw-joelmut commented
We should have at least one pipeline test for Facebook and WebEx yamls.

2020-09-04 12:35 UTC, denscollo commented
Promoted

2020-09-04 13:19 UTC, ceciliaavila approved these changes

2020-09-04 13:28 UTC, sw-joelmut approved these changes

2020-09-08 19:44 UTC, denscollo approved these changes

2020-09-08 19:46 UTC, denscollo commented
promoted

2020-09-08 19:46 UTC, closed without merging