Migrate Microsoft.Bot.Builder.TemplateManager.Tests to xUnit
southworks/botbuilder-dotnet pull request #323
Opened 2020-09-02 20:21 UTC by sw-joelmut

Fixes # 4098

## Description
This PR migrates all [Microsoft.Bot.Builder.TemplateManager](https://github.com/microsoft/botbuilder-dotnet/tree/main/tests/Microsoft.Bot.Builder.TemplateManager) tests from **MSTest** to **xUnit**.

## Specific Changes
- Replaced `MSTest` packages with `xUnit` in the `.csproj`.
- Changed `[TestCategory("Template")]` to `[Trait("TestCategory", "Template")]`.
- Changed `Assert.AreEqual` to `Assert.Equal`.
- Changed `TestContext.TestName` to include directly the name of the test.
- Implemented `TemplateFixture` class to share data context among tests.

## Testing
In the following image there are the passing tests.
![image](https://user-images.githubusercontent.com/62260472/92032013-e04bad80-ed3f-11ea-97ad-305f3994ca33.png)

2020-09-03 12:38 UTC, ceciliaavila requested changes

2020-09-03 12:38 UTC, ceciliaavila commented on tests/Microsoft.Bot.Builder.TemplateManager/TemplateManagerTests.cs
> +        private readonly TemplateFixture templateFixture;
Private member should start with `_`
```suggestion
        private readonly TemplateFixture _templateFixture;
```

2020-09-03 12:38 UTC, ceciliaavila commented on tests/Microsoft.Bot.Builder.TemplateManager/TemplateManagerTests.cs
> +            Assert.Equal(1, templateManager.List().Count);
Can we use `single` in here?
```suggestion
            Assert.Single(templateManager.List());
```

2020-09-03 12:38 UTC, ceciliaavila commented on tests/Microsoft.Bot.Builder.TemplateManager/TemplateManagerTests.cs
> +            Assert.Equal(1, templateManager.List().Count);
Same in here
```suggestion
            Assert.Single(templateManager.List());
```

2020-09-03 12:38 UTC, ceciliaavila commented on tests/Microsoft.Bot.Builder.TemplateManager/TemplateManagerTests.cs
> +#pragma warning disable SA1402
I think we should move this class to its own file.

2020-09-04 13:22 UTC, denscollo commented
Promoted

2020-09-04 13:22 UTC, closed without merging