Add missing XML documentation to Bot.Builder.Dialogs.Adaptive/TriggerConditions
southworks/botbuilder-dotnet pull request #332
Opened 2020-09-04 20:12 UTC by santgr11

Address # 4321

## Description
This PR adds the missing XML documentation to all visible classes, methods, properties, and parameters in [Bot.Builder.Dialogs.Adaptive/TriggerConditions](https://github.com/microsoft/botbuilder-dotnet/tree/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions), removing 75 errors.

**Note**: the NoWarn-CS1591 property is removed in the last PR of the series adding the documentation, to avoid build failures.

## Specific Changes
- Adds all missing documentation instances to all *.cs* files found within *Microsoft.Bot.Builder.Dialogs.Adaptive* TriggerConditions directory.

## Testing
Below you can see the number of errors shown before and after the changes when de NoWarn-CS1591 property is removed.
![image](https://user-images.githubusercontent.com/38112957/92280654-42d3b380-eed0-11ea-8f8e-fb8547d47a3f.png)

2020-09-07 19:59 UTC, sw-joelmut approved these changes

2020-09-07 20:28 UTC, iscaltritti-sw approved these changes

2020-09-07 20:35 UTC, ceciliaavila requested changes

2020-09-07 20:35 UTC, ceciliaavila commented on libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnCondition.cs
> +        /// <param name="actions">Optional, actions to add to the plan when the rule constraints are met.</param>
The order of the parameters is wrong.

2020-09-07 20:35 UTC, ceciliaavila commented on libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnCondition.cs
> +        /// Enumerate child dialog dependencies so they can be added to the containers dialog set.
```suggestion
        /// Enumerates child dialog dependencies so they can be added to the containers dialog set.
```

2020-09-07 20:35 UTC, ceciliaavila commented on libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnContinueConversation.cs
> +        /// Get the expression for this rule.
```suggestion
        /// Gets the expression for this rule.
```

2020-09-07 20:35 UTC, ceciliaavila commented on libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnDialogEvent.cs
> +        /// Get the expression for this rule.
```suggestion
        /// Gets the expression for this rule.
```

2020-09-07 20:35 UTC, ceciliaavila commented on libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnIntent.cs
> +        /// Get the expression for this rule.
```suggestion
        /// Gets the expression for this rule.
```

2020-09-08 19:46 UTC, ceciliaavila approved these changes

2020-09-10 18:47 UTC, denscollo approved these changes

2020-09-11 19:50 UTC, denscollo commented
Promoted

2020-09-11 19:50 UTC, closed without merging