Add missing XML documentation to Bot.Builder.Dialogs.Adaptive Functions, Generators, Input, Memory, Selectors and Templates folders
southworks/botbuilder-dotnet pull request #335
Opened 2020-09-04 20:40 UTC by santgr11

Address # 4321

## Description
This PR adds the missing XML documentation to all visible classes, methods, properties, and parameters in the *Bot.Builder.Dialogs.Adaptive* Functions, Generators, Input, Memory, Selectors, and Templates folders, removing 96 errors.

Note: the NoWarn-CS1591 property is removed in the last PR of the series adding the documentation to avoid build failures.

## Specific Changes
- Adds all missing documentation instances to all *.cs* files found within: 
  - [*Microsoft.Bot.Builder.Dialogs.Adaptive* Functions directory](https://github.com/microsoft/botbuilder-dotnet/tree/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Functions).
  - [*Microsoft.Bot.Builder.Dialogs.Adaptive* Generators directory](https://github.com/microsoft/botbuilder-dotnet/tree/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators).
  - [*Microsoft.Bot.Builder.Dialogs.Adaptive* Input directory](https://github.com/microsoft/botbuilder-dotnet/tree/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input).
  - [*Microsoft.Bot.Builder.Dialogs.Adaptive* Memory directory](https://github.com/microsoft/botbuilder-dotnet/tree/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory).
  - [*Microsoft.Bot.Builder.Dialogs.Adaptive* Selectors directory](https://github.com/microsoft/botbuilder-dotnet/tree/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors).
  - [*Microsoft.Bot.Builder.Dialogs.Adaptive* Templates directory](https://github.com/microsoft/botbuilder-dotnet/tree/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Templates).

## Testing
Below you can see the number of errors shown before and after the changes when de NoWarn-CS1591 property is removed.
![image](https://user-images.githubusercontent.com/38112957/92282698-8b8d6b80-eed4-11ea-993e-c1094035ce73.png)

2020-09-07 17:02 UTC, ceciliaavila requested changes

2020-09-07 18:58 UTC, iscaltritti-sw commented on libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs
> +        /// Called when a child dialog completed this turn, returning control to this dialog.
This one was taken directly from Dialog.cs, line 120. However, I agree with the change.

2020-09-07 19:08 UTC, iscaltritti-sw commented on libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Expressions/DialogExpression.cs
> +        /// Sets the value.
Taken from base file ExpressionProperty.cs ln149. I'll look up the _value_'s purpose to improve on the definition.

2020-09-07 19:25 UTC, ceciliaavila requested changes
There are still some files under /Selectors folder that need the fix `Initialize` -> `Initializes` and `Select` -> `Selects`

2020-09-07 20:00 UTC, iscaltritti-sw commented
> There are still some files under /Selectors folder that need the fix `Initialize` -> `Initializes` and `Select` -> `Selects`

My oversight, addressed on the latest commit!

2020-09-07 20:31 UTC, sw-joelmut requested changes

2020-09-07 20:31 UTC, sw-joelmut commented on libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/ResourceMultiLanguageGenerator.cs
> +        /// resource id.
Could we change it to title case?
```suggestion
        /// Resource id.
```

2020-09-07 20:31 UTC, sw-joelmut commented on libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs
> +        /// user replies with a new activity.
Same as in PR 331 https://github.com/southworks/botbuilder-dotnet/pull/331#discussion_r484559583

2020-09-08 19:00 UTC, santgr11 commented on libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/LanguageGeneratorManager.cs
> +        /// <returns>resolver.</returns>
The return could be changed to something better
```suggestion
        /// <returns>An instance of <see cref="ImportResolverDelegate">.</returns>
```

O
```suggestion
        /// <returns>The delegate to resolve the resource.</returns>
```

2020-09-08 19:00 UTC, santgr11 commented on libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/AttachmentInput.cs
> +        /// Called when input has been received, override this method to customize recognition of the input.
Since this is already an override, I'm not sure the part about overriding it should be there.

2020-09-08 19:00 UTC, santgr11 commented on libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Expressions/Converters/DialogExpressionConverter.cs
> +        /// true.
maybe add <c> tag to the true value, to represent its a value itself and that's why its not capitalized

2020-09-08 19:00 UTC, santgr11 commented on libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Expressions/DialogExpression.cs
> +        /// <param name="dialogIdOrExpression">string to convert to a <see cref="DialogExpression"/></param>
Capitalize the first word

2020-09-08 19:17 UTC, iscaltritti-sw approved these changes
Approving in place of @santgr11, since he authored the request.

2020-09-08 20:54 UTC, ceciliaavila approved these changes

2020-09-10 18:52 UTC, denscollo approved these changes

2020-09-11 19:45 UTC, denscollo commented
Promoted

2020-09-11 19:45 UTC, closed without merging