Migrate Microsoft.Bot.Builder.Dialogs.Adaptive.Tests to xUnit
southworks/botbuilder-dotnet pull request #337
Opened 2020-09-07 18:35 UTC by sw-joelmut

Fixes # 4093

## Description
This PR migrates all [Microsoft.Bot.Builder.Dialogs.Adaptive](https://github.com/microsoft/botbuilder-dotnet/tree/main/tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests) tests from **MSTest** to **xUnit**.

## Specific Changes
- Replaced `MSTest` packages with `xUnit` in the `.csproj`.
- Changed `[TestMethod]` to `[Fact]`.
- Changed `Assert.AreEqual` to `Assert.Equal`.
- Changed `Assert.IsNotNull` to `Assert.NotNull`.
- Changed `Assert.IsNull` to `Assert.Null`.
- Added `[assembly: TestFramework("Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.Tests.Startup", "Microsoft.Bot.Builder.Dialogs.Adaptive.Tests")]` to the `Startup` class to replace `[AssemblyInitialize]`.
- Implemented `ResourceExplorerFixture` class to share the `ResourceExplorer` among tests.
- Implemented `ConfigurationFixture` class to share the `Configuration` among tests.
- Improved tests Assertions.

## Testing
In the following image there are the passing tests.
![image](https://user-images.githubusercontent.com/62260472/92411702-56c12480-f11f-11ea-9576-c0732658735f.png)

2020-09-07 19:54 UTC, ceciliaavila requested changes

2020-09-07 19:54 UTC, ceciliaavila commented on tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
> +            var version2 = ds2.GetInternalVersion_Test();
I think we should keep this as it was.

2020-09-07 19:54 UTC, ceciliaavila commented on tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ConfigurationFixture.cs
> +﻿using System;
Don't forget to add the copyright header in every new file.

2020-09-07 19:54 UTC, ceciliaavila commented on tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ResourceExplorerFixture.cs
> +﻿using System;
Add the copyright header please.

2020-09-08 18:52 UTC, iscaltritti-sw approved these changes

2020-09-08 19:26 UTC, santgr11 approved these changes
lgtm

2020-09-09 20:03 UTC, ceciliaavila approved these changes

2020-09-10 18:56 UTC, denscollo approved these changes

2020-09-10 19:00 UTC, denscollo commented
Promoted

2020-09-10 19:00 UTC, closed without merging