[Slack Adapter] Make messages with attachments into message activities
southworks/botbuilder-dotnet pull request #367
Opened 2021-03-08 11:52 UTC by iscaltritti-sw

Fixes # 4888

## Description
Updates the Slack Adapter to resolve received messages with attachments as `ActivityTypes.Message`, allowing users to access the _text_ and _attachment_ properties from the root activity.

**THIS IS A BREAKING CHANGE 
Messages with attachments will be received "on message" activities instead of "on event" activities.**

## Specific Changes

  - Adds received messages with attachments to the filter to resolve them as message activities.
    - Obtains each file's properties manually to parse them into `Attachments`

## Testing
The changes were tested in unit and functional tests with no issues, since there are no message with attachment tests affected.
![image](https://user-images.githubusercontent.com/64803884/110172139-76d65580-7ddb-11eb-9d66-b8a32074d9cc.png)

2021-03-08 11:54 UTC, iscaltritti-sw commented
To be promoted as draft

2021-03-08 12:18 UTC, ceciliaavila requested changes

2021-03-08 12:18 UTC, ceciliaavila commented on libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackHelper.cs
> +using Newtonsoft.Json;
This is not necessary.

2021-03-08 12:24 UTC, iscaltritti-sw commented
Change pushed, thanks @ceciliaavila

2021-03-08 12:26 UTC, santgr11 commented
Could we add a comparison of how the activity looked like before and after? Or just the new one when it is inside the OnMessage

2021-03-08 12:27 UTC, ceciliaavila approved these changes

2021-03-08 13:12 UTC, iscaltritti-sw commented
> Could we add a comparison of how the activity looked like before and after? Or just the new one when it is inside the OnMessage
@santgr11 

Added a comparison image between ABS and the new model for the activity "OnMessage".

2021-03-08 13:14 UTC, santgr11 approved these changes

2021-03-09 20:59 UTC, denscollo commented
Promoted

2021-03-09 20:59 UTC, closed without merging