Add local compare script
southworks/botbuilder-dotnet pull request #370
Opened 2021-04-06 16:06 UTC by MartinLuccanera

## Description
Adds a script that enables devs to locally check binaries for compatibility issues via usage of [ApiCompat](https://github.com/dotnet/arcade/tree/main/src/Microsoft.DotNet.ApiCompat).

## Specific Changes
  - Updated `botbuilder-dotnet-ci.yml`. Added variable to run apiCompat script only if building locally.
  - Added `ExecuteApiCompat.ps1` . Script that downloads and installs dependencies to check for compatibility issues.
  - Updated `README.md` with information related to local ApiCompat script.
  - Updated `Directory.Build.props`. Added ApiCompat version property to pass as parameter to the script.
  - Updated `.gitignore` to ignore ApiCompat generated folders.
  - Added ApiCompat script to run as a post-build event for all relevant projects.
  - Added `PackageId` property for the following projects where it was missing:
       - Microsoft.Bot.Builder.Azure.csproj
       - Microsoft.Bot.Builder.Dialogs.csproj
       - Microsoft.Bot.Builder.TemplateManager.csproj
       - Microsoft.Bot.Schema.csproj
       - Microsoft.Bot.Builder.Integration.AspNet.Core.csproj

2021-04-15 12:18 UTC, ceciliaavila requested changes
Let's change the title to something like `[API Compat][#4810] Enable developers to perform binary compatibility check on local machine`

2021-04-15 12:18 UTC, ceciliaavila commented on build/ExecuteApiCompat.ps1
> +  Specifies the version of the library to compare the implementation with..
```suggestion
  Specifies the version of the library to compare the implementation with.
```

2021-04-15 13:46 UTC, ceciliaavila approved these changes

2021-04-15 14:59 UTC, sw-joelmut approved these changes
The Build locally passed with the latest changes and show no errors, nice!

2021-04-16 21:16 UTC, santgr11 approved these changes

2021-04-21 12:58 UTC, denscollo approved these changes

2021-04-21 13:11 UTC, denscollo commented
The name of the branch is not okay, take into consideration that we always use the format southworks/(add,update,fix,remove,etc.)/feature

2021-04-21 14:23 UTC, closed without merging