[#384][Part 2] Increase Microsoft.Bot.Streaming code coverage
southworks/botbuilder-dotnet pull request #386
Opened 2021-07-27 20:52 UTC by sw-joelmut

Addresses #384  (SW Repo)

## Description
This PR increases the code coverage for the `Microsoft.Bot.Streaming` from **63%** up to **84%**, the changes are divided in two parts, see PR #385 (SW Repo) for Part 1.

## Specific Changes
- Added unit tests for:
  - ConcurrentStream
  - ContentStream
  - NamedPipe
  - NamedPipTransport
  - Request
  - Response
  - SendOperations
  - TransportDisconnected
  - WebSocketTransport

## Testing
The following image shows the before and after the changes that increased the code coverage.
![imagen](https://user-images.githubusercontent.com/62260472/127224473-770d1e5a-65e5-4555-bb65-55e3ffcb38d2.png)

2021-07-28 16:26 UTC, sw-joelmut commented
Pipeline run: https://dev.azure.com/joelmut93/manx-pipeline-testing/_build/results?buildId=683&view=results

2021-07-29 13:25 UTC, ceciliaavila requested changes

2021-07-29 13:25 UTC, ceciliaavila commented on tests/Microsoft.Bot.Streaming.Tests/TransportDisconnectedExceptionTests.cs
> +using System.Threading.Tasks;
These are not needed.

2021-07-29 13:25 UTC, ceciliaavila commented on tests/Microsoft.Bot.Streaming.Tests/WebSocketTransportTests.cs
> +            var requestHandlerMock = new Mock<RequestHandler>();
This line can be removed.

2021-07-29 19:49 UTC, sw-joelmut commented
@ceciliaavila feedback applied, thanks

2021-07-29 19:55 UTC, ceciliaavila approved these changes

2021-08-02 19:25 UTC, MartinLuccanera approved these changes

2021-08-05 15:03 UTC, GiulianoDolceTalianoSantoro approved these changes

2021-08-13 19:57 UTC, ceciliaavila commented
Promoted to MS in PR# 5840

2021-08-13 19:57 UTC, closed without merging