Increase Microsoft.Bot.Builder.AI.Orchestrator code coverage #390
southworks/botbuilder-dotnet pull request #391
Opened 2021-09-23 18:43 UTC by MartinLuccanera

Fixes # XXXX

## Description
This PR increases the code coverage for the `Microsoft.Bot.Builder.AI.Orchestrator` library from **62%** to **88%**.

## Specific Changes
Added unit tests for the following classes:
- OrchestratorRecognizer
- OrchestratorBotComponent

## Testing
The following image shows the new code coverage.
![image](https://user-images.githubusercontent.com/18757147/134564894-fd2ed176-7085-4f3f-8b74-d8bbe9591bc2.png)

2021-09-23 19:48 UTC, ceciliaavila requested changes

2021-09-23 19:48 UTC, ceciliaavila commented on tests/Microsoft.Bot.Builder.AI.Orchestrator.Tests/OrchestratorBotComponentTests.cs
> +using Microsoft.Bot.Schema;
This line can be removed.

2021-09-23 19:48 UTC, ceciliaavila commented on tests/Microsoft.Bot.Builder.AI.Orchestrator.Tests/OrchestratorRecognizerTest.cs
> +    public class OrchestratorRecognizerTest
This class should be named OrchestratorRecognizerTest**s**

2021-09-23 19:48 UTC, ceciliaavila commented on tests/Microsoft.Bot.Builder.AI.Orchestrator.Tests/OrchestratorRecognizerTest.cs
> +        public async Task LogsTelemetryThrowsArgumentNullExcetionOnNullDialogContext()
```suggestion
        public async Task LogsTelemetryThrowsArgumentNullExceptionOnNullDialogContext()
```

2021-09-24 13:31 UTC, sw-joelmut commented on tests/Microsoft.Bot.Builder.AI.Orchestrator.Tests/OrchestratorAdaptiveRecognizerTests.cs
> +            });
I see you already passing the `ModelFolder` and `SnapshotFile` through the `OrchestratorRecognizer`, is the properties with the `new StringExpression("C:/")` instance even needed or vice-versa?

2021-09-24 13:38 UTC, sw-joelmut commented
We should have a different naming for the branch when we promote it to MS. Additionally, for this case, we are creating a separate issue for each library we add tests and then relate that to the parent.
eg for naming and pr/issue: `https://github.com/microsoft/botbuilder-dotnet/pull/5890`
Also, the name of the PR has the `#390` at the end, we tend to put it at the start with [#XXX]
![image](https://user-images.githubusercontent.com/62260472/134683188-9755cc39-6fcf-459f-a6d0-d0951116417a.png)

2021-09-27 17:45 UTC, closed without merging

2021-09-27 17:46 UTC, MartinLuccanera commented
Moved to a new PR https://github.com/southworks/botbuilder-dotnet/pull/394