[#6292] Update CosmosDbPartitionedStorage from Functional to Unit tests
southworks/botbuilder-dotnet pull request #442
Opened 2022-04-12 15:52 UTC by sw-joelmut

Addresses # 6292

## Description
This PR removes the existing Functional tests and as a replacement, it adds support for internal testing to the `CosmosDbPartitionedStorage` class, and introduces all the necessary unit tests, increasing the **code coverage up to 86%**.

## Specific Changes
- Updates the `CosmosDbPartitionedStorage` class, adding a new internal constructor.
- Updates the `CosmosDbPartitionedStorage.DocumentStoreItem` class accessibility from `private` to `internal`, so it can be accessed from the tests.
- Removed all the existing tests in `CosmosDbPartitionStorageTests` class.
- Adds new unit tests to the `CosmosDbPartitionStorageTests` class for each method, constructor, method validations, etc.

## Testing
The following image shows the new unit tests and the code coverage.
![image](https://user-images.githubusercontent.com/62260472/163000102-421f760c-b799-4b5f-b90c-38bb95f80485.png)

2022-04-13 13:00 UTC, ceciliaavila requested changes

2022-04-13 19:31 UTC, sw-joelmut commented on tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbPartitionStorageTests.cs
> +            await _storage.WriteAsync(new Dictionary<string, object>());
Its a validation if the dictionary is empty, it doesn't continue executing the code, it simply return

2022-04-13 19:33 UTC, sw-joelmut commented on tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbPartitionStorageTests.cs
> +using System.Net;
Nice catch!, didn't see that

2022-04-13 19:45 UTC, sw-joelmut commented
Changes pushed, thanks! @ceciliaavila

2022-04-13 19:47 UTC, ceciliaavila approved these changes

2022-04-22 17:52 UTC, erquirogasw approved these changes

2022-04-25 17:33 UTC, sw-joelmut commented
/promoted 6302

2022-04-25 17:33 UTC, closed without merging