[#6292] Update CosmosDbStorage from Functional to Unit tests
southworks/botbuilder-dotnet pull request #443
Opened 2022-04-13 19:26 UTC by sw-joelmut

Addresses # 6292

## Description
This PR removes the existing Functional tests and as a replacement, it adds support for internal testing to the `CosmosDbStorage` class, and introduces all the necessary unit tests, increasing the **code coverage up to 86%**.

## Specific Changes
- Updates the `CosmosDbStorage.DocumentStoreItem` class accessibility from `private` to `internal`, so it can be accessed from the tests.
- Removed all the existing tests in `CosmosDbStorageTests` class.
- Adds new unit tests to the `CosmosDbStorageTests` class for each method, constructor, method validations, etc.

## Testing
The following image shows the new unit tests and the code coverage.
![image](https://user-images.githubusercontent.com/62260472/163255258-d02e12e0-f8b7-412d-ac8a-ec7f1ccde338.png)

2022-04-22 16:13 UTC, erquirogasw approved these changes

2022-04-22 16:55 UTC, ceciliaavila requested changes

2022-04-22 16:55 UTC, ceciliaavila commented on tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbStorageTests.cs
> +        private readonly string _authKey = "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==";
This can be a constant.

2022-04-22 17:19 UTC, ceciliaavila requested changes

2022-04-22 17:19 UTC, ceciliaavila commented on tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbStorageTests.cs
> +        private readonly Uri _cosmosDBEndpoint = new Uri("https://localhost:8081");
```suggestion
        private readonly Uri _cosmosDbEndpoint = new Uri("https://localhost:8081");
```

2022-04-22 18:13 UTC, sw-joelmut commented
@ceciliaavila applied, thanks!

2022-04-22 18:15 UTC, ceciliaavila approved these changes

2022-04-25 17:34 UTC, sw-joelmut commented
/promoted 6303

2022-04-25 17:34 UTC, closed without merging