[#6292] Add unit tests to cover AzureBlobTranscriptStore fixed
southworks/botbuilder-dotnet pull request #449
Opened 2022-04-26 12:19 UTC by erquirogasw

Fixes # 6292

## Description
This PR adds a new constructor that uses CloudlobDirectory v10.0.3 constructor. Also, adds unit tests for AzureBlobTranscriptStore .

## Specific Changes
Microsoft.Azure.Storage.Blob updated to 10.0.3
New constructor that uses CloudBlobDirectory constructor of version 10.0.3

New tests added:
- GetTranscriptActivitiesAsyncContinuationToken
- GetTranscriptActivitiesAsyncMultipleBlobs
- GetTranscriptActivitiesAsyncWithMetadata
- LogActivityAsyncInternalFindActivityBlobAsync

## Testing
This image shows the unit tests passing
<img width="357" alt="image" src="https://user-images.githubusercontent.com/64815358/165150064-0ca8436c-abd3-4e26-a4ed-997111a38574.png">

2022-04-26 13:01 UTC, ceciliaavila requested changes
Let's change:
This PR adds a new constructor that uses CloudlobDirectory v10.0.3 constructor. Also, adds unit tests for AzureBlobTranscriptStore
With:
This PR adds unit tests for the AzureBlobTranscriptStore class.
  
And in _Detailed Changes_:
- Adds unit tests for the AzureBlobTranscriptStore class
- Adds a new internal constructor that receives a CloudBlobClient to be able to pass a mocked instance of this class, allowing to test without the use of emulators.
- Updates the Microsoft.Azure.Storage.Blob package to version 10.3.0 to be able to use the public constructor of CloudBlobDirectory introduced in this version and mock this class.

2022-04-26 15:46 UTC, ceciliaavila approved these changes

2022-04-27 12:50 UTC, sw-joelmut requested changes

2022-04-28 13:13 UTC, sw-joelmut approved these changes

2022-04-28 17:51 UTC, ceciliaavila commented
/promoted 6311

2022-04-28 17:51 UTC, closed without merging