Obsolete channels marked as deprecated.
southworks/botbuilder-dotnet pull request #461
Opened 2022-05-23 20:09 UTC by erquirogasw

Addresses # 6448
#minor

## Description
This PR marks the unsupported channels as deprecated.
Unsupported channels:
- Console
- Cortana
- Kik
- SkypeForBusiness
- Telephony

## Specific Changes
- Unsupported channels marked as deprecated in Microsoft.Bot.Connector/Channels.cs

## Testing
This screenshot shows the unit tests passing
<img width="498" alt="image" src="https://user-images.githubusercontent.com/64815358/169897665-377b3037-e0ad-4742-8ce5-7dbd25167427.png">

2022-05-23 20:53 UTC, ceciliaavila requested changes
Please update the issue number. I created the issue `[# 6339] Mark deprecated channels as obsolete in Channels enum` in BotBuilder-DotNet

2022-05-24 12:28 UTC, erquirogasw commented
> Please update the issue number. I created the issue `[# 6339] Mark deprecated channels as obsolete in Channels enum` in BotBuilder-DotNet

Done

2022-05-24 12:30 UTC, ceciliaavila approved these changes

2022-05-27 11:45 UTC, ceciliaavila commented
/promoted 6343

2022-05-27 11:45 UTC, closed without merging