Fix CodeQL SM02211 alert - SerializationBinder
southworks/botbuilder-dotnet pull request #495
Opened 2022-11-11 13:36 UTC by sw-joelmut

#minor
Fixes #
6515
6516
6517
6519
6520

## Description
This PR fixes the CodeQL SM02211 alert related to unsafe `JsonSerializer` `TypeNameHandling` usage.
For these cases, it implements a custom [SerializationBinder](https://www.newtonsoft.com/json/help/html/SerializeSerializationBinder.htm), allowing only the types that are defined in the configuration or related ones.

## Specific Changes
- Adds the `AllowedTypesSerializationBinder` class to allow only types that are defined in the instance.
- Adds tests for the `AllowedTypesSerializationBinder` class.
- Updated `BlobsStorage`, `AzureBlobStorage`, and `CosmosDbPartitionedStorage` classes to implement the binder.
- Updated `BlobsTranscriptStore` setting the `TypeNameHandling` to None.

## Testing
The following image shows the tests passing successfully and the error message when a type isn't allowed by the process.
![image](https://user-images.githubusercontent.com/62260472/201351257-5b7ebd7c-3712-4767-abaf-d7bb0b678d34.png)
![image](https://user-images.githubusercontent.com/62260472/201351262-2b76cae3-9b0b-4462-a772-9dde452731c9.png)

2022-11-11 14:30 UTC, ceciliaavila requested changes

2022-11-11 14:30 UTC, ceciliaavila commented on libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsStorage.cs
> +using System.Linq;
This using is not necessary.

2022-11-11 14:30 UTC, ceciliaavila commented on libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs
> +using System.Linq;
Same here.

2022-11-11 14:30 UTC, ceciliaavila commented on libraries/Microsoft.Bot.Builder/AllowedTypesSerializationBinder.cs
> +            // Return Type when it have Interfaces.
```suggestion
            // Return Type when it has Interfaces.
```

2022-11-11 17:55 UTC, sw-joelmut commented
@ceciliaavila changes applied, thanks

2022-11-11 19:27 UTC, ceciliaavila approved these changes

2022-11-11 19:58 UTC, erquirogasw approved these changes

2022-11-14 13:22 UTC, sw-joelmut commented
/promoted 6549

2022-11-14 13:22 UTC, closed without merging