[#6589] Replace ADAL with MSAL internally
southworks/botbuilder-dotnet pull request #508
Opened 2023-03-15 21:05 UTC by sw-joelmut

Fixes # 6589

## Description
This PR migrates ADAL related functionality to MSAL internally.

> **Note:** The public `JwtTokenProviderFactory` class has been deprecated since its all related to ADAL functionality, said class is only being used for MSI classes, these classes will no longer use the deprecated provider and instead use the MSAL functionality.

## Specific Changes
- `AppCredentials.BuildAuthenticator` has been deprecated and the `BuildIAuthenticator` method should be used instead.
- Added `BuildIAuthenticator` method to the `CertificateAppCredentials` class, providing the MSAL authenticator instance, also the internal class variables have been changed to minimize the ADAL implementation without generating breaking changes.
- Deprecated `JwtTokenProviderFactory` since it's no longer used in MSI related classes internally. Related classes will redirect any constructor using the provider to the one without it.
- Updated the `ManagedIdentityAuthenticator` class to use MSAL functionality instead of `JwtTokenProviderFactory` to acquire the token.
- Added `BuildIAuthenticator` method to the `MicrosoftAppCredentials` class, providing the MSAL authenticator instance.
- Removed the `Microsoft.IdentityModel.Clients.ActiveDirectory` (ADAL) package reference from Connector, since it's no longer used.
    - The `Microsoft.Azure.Services.AppAuthentication` package reference that uses ADAL underneath couldn't be removed, since it will generate breaking changes.
 - Updated existing unit tests due to failures when providing and mocking the `JwtTokenProviderFactory` parameter class.
 - Added new unit tests to validate the new implementation works as expected.

## Testing
The following image shows a few bots working, the combination of skill bots and the [FunctionalTests](https://github.com/microsoft/BotFramework-FunctionalTests) pipeline passing successfully.
![image](https://user-images.githubusercontent.com/62260472/225437461-119b9eff-76b8-465b-a02e-d3b353b778c1.png)

2023-03-15 21:06 UTC, sw-joelmut commented
CI pipeline
![image](https://user-images.githubusercontent.com/62260472/225442636-1a7018cc-b878-446f-ae6a-15f7a472b992.png)
https://dev.azure.com/joelmut1333/functional-tests/_build/results?buildId=3313&view=results

2023-03-16 13:24 UTC, ceciliaavila requested changes

2023-03-16 18:32 UTC, sw-joelmut commented on libraries/Microsoft.Bot.Connector/Authentication/ConstantHttpClientFactory.cs
> +    internal class ConstantHttpClientFactory : Microsoft.IdentityModel.Clients.ActiveDirectory.IHttpClientFactory, IMsalHttpClientFactory
fixed thanks

2023-03-16 18:32 UTC, sw-joelmut commented on libraries/Microsoft.Bot.Connector/Authentication/ConstantHttpClientFactory.cs
>  using Microsoft.IdentityModel.Clients.ActiveDirectory;
fixed thanks

2023-03-16 18:33 UTC, ceciliaavila approved these changes

2023-03-17 17:33 UTC, erquirogasw approved these changes

2023-03-20 17:42 UTC, closed without merging