[#6644] Remove BotFrameworkAdapter Obsolete annotation
southworks/botbuilder-dotnet pull request #522
Opened 2023-06-14 16:40 UTC by JhontSouth

#minor

## Description
This PR removes the _**Obsolete**_ tags from the _BotFrameworkAdapter_ class and its related classes.

## Specific Changes
  - Removed tags and added the suggestion of the use of _CloudAdapter_ in the following classes:
    - BotMessageHandler 
    - BotFrameworkHttpAdapter
    - BotMessageHandlerBase
    - IAdapterIntegration
    - BotFrameworkHttpAdapterBase
    - BotFrameworkAdapter

2023-06-14 17:51 UTC, ceciliaavila requested changes

2023-06-14 17:51 UTC, ceciliaavila commented on libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
> +    /// A bot adapter that can connect a bot to a service endpoint.
Remove the extra space.

2023-06-15 18:02 UTC, erquirogasw approved these changes

2023-06-21 13:13 UTC, ceciliaavila commented
/promoted 6648

2023-06-21 13:13 UTC, closed without merging