Implementation of SendMessageToAllUsersInTeam Teams batch APIs
southworks/botbuilder-dotnet pull request #528
Opened 2023-07-10 19:51 UTC by JhontSouth

#minor

## Description
This PR implements the SendMessageToAllUsersInTeam method of the new Teams batch APIs in TeamsOperations.

- [x] Send message to a list of users
- [x] Send message to all users    in a tenant
- [x ] Send message to all users in a team
- [ ] Send message to a list of channels  
- [ ] Get Operation State
- [ ] Get failed entries paginated
- [ ] Cancel Operation

## Specific Changes
- Implemented the new methods of **_SendMessageToAllUsersInTeam_** in **_TeamsOperations_**, **_TeamsOperationsExtensions_**, and **_TeamsInfo_**.

2023-07-11 13:03 UTC, ceciliaavila requested changes

2023-07-11 16:42 UTC, ceciliaavila requested changes

2023-07-11 16:42 UTC, ceciliaavila commented on libraries/Microsoft.Bot.Connector/Teams/TeamsOperations.cs
> +    using System.Net.Http.Headers;
Having these two is redundant I think. Remove one.

2023-07-12 12:51 UTC, sw-joelmut requested changes

2023-07-12 12:51 UTC, sw-joelmut commented on libraries/Microsoft.Bot.Connector/Teams/TeamsOperations.cs
> +                        // This means the request was successfull. We can make our retry policy null.
successful

2023-07-13 13:04 UTC, merged