Implementation of SendMessageToListOfChannels Teams batch APIs
southworks/botbuilder-dotnet pull request #529
Opened 2023-07-10 20:17 UTC by JhontSouth

#minor

## Description
This PR implements the SendMessageToListOfChannels method of the new Teams batch APIs in TeamsOperations.

- [x] Send message to a list of users
- [x] Send message to all users    in a tenant
- [ ] Send message to all users in a team
- [x] Send message to a list of channels  
- [ ] Get Operation State
- [ ] Get failed entries paginated
- [ ] Cancel Operation

## Specific Changes
- Implemented the new methods of **_SendMessageToListOfChannels_** in **_TeamsOperations_**, **_TeamsOperationsExtensions_**, and **_TeamsInfo_**.

2023-07-11 13:14 UTC, ceciliaavila requested changes

2023-07-11 16:43 UTC, ceciliaavila approved these changes

2023-07-12 12:57 UTC, sw-joelmut requested changes

2023-07-12 12:57 UTC, sw-joelmut commented on libraries/Microsoft.Bot.Connector/Teams/TeamsOperations.cs
> +                        // This means the request was successfull. We can make our retry policy null.
successful

2023-07-13 13:54 UTC, merged