fix: Add Audience for Certificate auth to work with Skills
southworks/botbuilder-dotnet pull request #563
Opened 2024-05-22 18:31 UTC by sw-joelmut

#minor

## Description
This PR adds Audience to CertificateAppCredentials, so it is passed correctly when calling a Skill bot. Additionally, these changes take into consideration the PR# https://github.com/microsoft/botbuilder-dotnet/pull/ 6694, so the improvement isn't lost in the process.

## Specific Changes
  - Added missing `oAuthScope` parameter to `libraries/Microsoft.Bot.Connector/Authentication/CertificateAppCredentials.cs`.
  - Improved `libraries/Microsoft.Bot.Connector/Authentication/CertificateServiceClientCredentialsFactory.cs` by reverting the changes made in the PR# https://github.com/microsoft/botbuilder-dotnet/pull/ 6694, but maintaining the improvement.
    - It creates a new instance of `CertificateAppCredentials` per Audience, instead of having just one with the default `api.botframework`.
  - Added unit test to confirm it doesn't create new instances when the same Audience is provided.

## Testing
The following images show the new unit test passing and the Root + Skill bots working as expected.
![image](https://github.com/southworks/botbuilder-dotnet/assets/62260472/c02bea3e-3d48-4379-a049-b58f43bd233b)
![image](https://github.com/southworks/botbuilder-dotnet/assets/62260472/d781e1c5-7226-4da7-926e-c86d100b08f1)

2024-05-22 18:31 UTC, sw-joelmut commented
![image](https://github.com/southworks/botbuilder-dotnet/assets/62260472/5a7cec57-8f00-422a-a98e-61a5444b0c26)

2024-05-22 19:57 UTC, JhontSouth approved these changes

2024-05-22 20:27 UTC, andres-robinet-sw requested changes
* Check cache usage (a.k.a. `ConcurrentDictionary`). `TryGetValue` followed by `TryAdd` is not thread-safe.
* `GetOrAdd` is safer: The value factory could end up being invoked more than once, thus creating two instances of `CertificateAppCredentials`. However, you are guaranteed to obtain the instance of `CertificateAppCredentials` that is being added to the dictionary on *every* thread (the other instances, if created, will be garbage collected).

2024-05-22 20:27 UTC, andres-robinet-sw commented on libraries/Microsoft.Bot.Connector/Authentication/CertificateServiceClientCredentialsFactory.cs
> +            }
Potential concurrency issue. Use [GetOrAdd](https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.getoradd?view=netstandard-2.1#examples) to ensure concurrent dictionary thread safety.
```csharp
var certificateAppCredentials = _certificateAppCredentialsByAudience.GetOrAdd(audience, (aud) =>
    new CertificateAppCredentials(
        _certificate,
        _appId,
        _tenantId,
        audience,
        _sendX5c,
        _httpClient,
        _logger)
);
```

2024-05-27 14:49 UTC, sw-joelmut commented
/promoted 6794

2024-05-27 14:49 UTC, closed without merging