bump: Update old packages
southworks/botbuilder-dotnet pull request #571
Opened 2024-07-25 14:30 UTC by JhontSouth

#minor

## Description
This PR upgrades old packages that don't have conflicts with BotBuilder in their latest versions.

## Specific Changes
  - Updated the following packages:
      - AdaptiveCards 
      - Azure.Storage.Blobs 
      - Azure.Storage.Queues 
      - BenchmarkDotNet 
      - coverlet.collector 
      - coverlet.msbuild
      - JsonPath.Net 
      - Microsoft.ApplicationInsights 
      - Microsoft.ApplicationInsights.AspNetCore 
      - Microsoft.ApplicationInsights.DependencyCollector 
      - Microsoft.ApplicationInsights.PerfCounterCollector 
      - Microsoft.ApplicationInsights.TraceListener 
      - Microsoft.ApplicationInsights.Web 
      - Microsoft.ApplicationInsights.WindowsServer 
      - Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel 
      - Microsoft.AspNet.WebApi 
      - Microsoft.AspNetCore.Hosting.Abstractions 
      - Microsoft.AspNetCore.Http 
      - Microsoft.AspNetCore.Mvc.Core 
      - Microsoft.AspNetCore.Mvc.Formatters.Json 
      - Microsoft.AspNetCore.Mvc.NewtonsoftJson 
      - Microsoft.AspNetCore.Mvc.Testing
      - Microsoft.Azure.Cosmos
      - Microsoft.CodeAnalysis.CSharp.Scripting
      - Microsoft.CSharp 
      - Microsoft.Extensions.Configuration 
      - Microsoft.Extensions.Configuration.Json 
    - Microsoft.Extensions.Configuration.UserSecrets 
    - Microsoft.Extensions.DependencyInjection
    - Microsoft.IdentityModel.Protocols.OpenIdConnect 
    - Microsoft.IdentityModel.Tokens
    - Microsoft.NET.Test.Sdk
    - MSTest.TestAdapter 
    - MSTest.TestFramework 
    - NAudio 
    - Newtonsoft.Json
    - NuGet.Packaging 
    - NunitXml.TestLogger 
    - ReportGenerator
    - SlackAPI 
    - System.Drawing.Common 
    - System.IdentityModel.Tokens.Jwt 
    - System.IO.Pipelines 
    - System.Net.Security 
    - System.Text.Encodings.Web 
    - xunit.runner.visualstudio 
    - XunitXml.TestLogger  

## Testing
The following image shows the unit tests working after the updates.
![image](https://github.com/user-attachments/assets/360789e1-2c95-42d6-a7cc-a269b66aca93)

2024-07-25 19:44 UTC, sw-joelmut requested changes

2024-07-25 19:44 UTC, sw-joelmut commented on tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/Microsoft - Backup.Bot.Builder.Adapters.Slack.Tests.csproj
I think this file doesnt go right?, it says Backup...

2024-07-25 19:44 UTC, sw-joelmut commented on tests/Adapters/Microsoft.Bot.Builder.Adapters.Twilio.Tests/Microsoft - Backup.Bot.Builder.Adapters.Twilio.Tests.csproj
Same for this file

2024-07-25 19:44 UTC, sw-joelmut commented on tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/Microsoft - Backup.Bot.Builder.Adapters.Webex.Tests.csproj
Same here

2024-07-25 19:44 UTC, sw-joelmut commented on tests/Microsoft.Bot.AdaptiveExpressions.Core.AOT.Tests/Microsoft - Backup.Bot.AdaptiveExpressions.Core.AOT.Tests.csproj
same here

2024-07-25 19:44 UTC, sw-joelmut commented on tests/Microsoft.Bot.AdaptiveExpressions.Core.Tests/Microsoft - Backup.Bot.AdaptiveExpressions.Core.Tests.csproj
same here

2024-07-25 19:44 UTC, sw-joelmut commented on tests/Microsoft.Bot.Builder.AI.LUIS.Tests/Microsoft - Backup.Bot.Builder.AI.Luis.Tests.csproj
same here

2024-07-25 19:44 UTC, sw-joelmut commented on tests/Microsoft.Bot.Builder.AI.Orchestrator.Tests/Microsoft - Backup.Bot.Builder.AI.Orchestrator.Tests.csproj
same here, check all Backup. files

2024-07-26 17:17 UTC, JhontSouth commented on tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/Microsoft - Backup.Bot.Builder.Adapters.Slack.Tests.csproj
I removed all the Backup files

2024-07-26 17:17 UTC, JhontSouth commented on tests/Microsoft.Bot.Builder.AI.Orchestrator.Tests/Microsoft - Backup.Bot.Builder.AI.Orchestrator.Tests.csproj
I removed all the Backup files

2024-07-30 19:48 UTC, sw-joelmut approved these changes

2024-07-31 14:50 UTC, JhontSouth commented
Promoted /6830

2024-07-31 14:50 UTC, closed without merging