fix: [#6861]TeamsSSOTokenExchangeMiddleware.DeduplicatedTokenExchangeIdAsync fails on BlobStorage ETag validation
southworks/botbuilder-dotnet pull request #590
Opened 2024-11-11 13:46 UTC by JhontSouth

Fixes # 6861
#minor

## Description
This PR adds the 412 error capture of the _BlobsStorage_ to be handled by _TeamsSSOTokenExchangeMiddleware_.

## Specific Changes
  - Added **_catch_** to capture 412 in _WriteAsync_ method of _BlobsStorage_.

## Testing
The following image shows the error being captured.
![image](https://github.com/user-attachments/assets/9e870161-e1a2-47ce-81d1-e0b215694adf)

2024-11-11 14:20 UTC, ceciliaavila requested changes

2024-11-11 14:20 UTC, ceciliaavila commented on libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsStorage.cs
> +                when (ex.Status == 412)
```suggestion
                when (ex.Status == (int)HttpStatusCode.PreconditionFailed)
```

2024-11-11 15:58 UTC, JhontSouth commented on libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsStorage.cs
> +                when (ex.Status == 412)
fixed

2024-11-11 16:00 UTC, ceciliaavila approved these changes

2024-11-12 12:42 UTC, JhontSouth commented
Promoted /6867

2024-11-12 12:42 UTC, closed without merging